# Banco de dados
spring.datasource.url=jdbc:postgresql://localhost:5432/catalogdb
spring.datasource.username=admin
spring.datasource.password=admin123

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Cache
spring.cache.type=redis